Remove vcpkg as a submodule and download/install Boost from source
NonStatic2014/onnxruntime pull request #39
Opened 2019-04-13 02:32 UTC by tmccrmck

2019-04-13 08:02 UTC, letmaik requested changes

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +set(BOOST_USE_STATIC_LIBS false)
Please make this configurable, e.g. by making it a cache variable.

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +	if(CMAKE_BUILD_TYPE MATCHES DEBUG)
`Debug`?

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +set(BoostSHA1 8f32d4617390d1c2d16f26a27ab60d97807b35440d45891fa340fc2648b04406)
Why not `BOOST_SHA1`?

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +			BUILD_COMMAND ./b2 install ${BOOST_MAYBE_STATIC} --prefix=${BOOST_ROOT_DIR} variant=${VARIANT} toolset=gcc ${BOOST_COMPONENTS_FOR_BUILD}
Don't hard-code gcc, should be inferred from `CMAKE_C_COMPILER_ID`.

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +			CONFIGURE_COMMAND ./bootstrap.sh --prefix=${BOOST_ROOT_DIR}
Either add a check that installing Boost is not supported on Windows, or add support for it.

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +	set(CMAKE_FIND_LIBRARY_PREFIXES ${CMAKE_STATIC_LIBRARY_PREFIX})
Remove this and the other `CMAKE_FIND_*` overrides, you don't use it.

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +	message(STATUS "Adding all Boost components")
Not really, only `${BOOST_COMPONENTS}`.

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +	set(BOOST_INCLUDE_DIR ${install_dir}/include)
Why the uppercase variant? I would just follow what FindBoost normally provides: https://cmake.org/cmake/help/v3.14/module/FindBoost.html

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +	set(BOOST_LIBRARYDIR ${install_dir}/lib)
Not necessary. Also, in FindBoost this is a search hint, not the resolved location.

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +	libraries_to_fullpath(BOOST_LIBRARIES)
Uppercase not necessary, just stick to what FindBoost would provide you.

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +	set(Boost_LIBRARIES ${BOOST_LIBRARIES})
Add `mark_as_advanced(Boost_LIBRARIES Boost_INCLUDE_DIR)`. Otherwise they are not cache variables and wouldn't be useable in downstream projects.

2019-04-13 08:02 UTC, letmaik commented on cmake/get_boost.cmake
> +	message(FATAL_ERROR "No COMPONENTS specified for Boost")
Fix file formatting: spaces, not tabs.

2019-04-15 18:34 UTC, tmccrmck commented on cmake/get_boost.cmake
> +set(BoostSHA1 8f32d4617390d1c2d16f26a27ab60d97807b35440d45891fa340fc2648b04406)
Changed.

2019-04-15 18:34 UTC, tmccrmck commented on cmake/get_boost.cmake
> +set(BOOST_USE_STATIC_LIBS false)
Done.

2019-04-15 18:35 UTC, tmccrmck commented on cmake/get_boost.cmake
> +			CONFIGURE_COMMAND ./bootstrap.sh --prefix=${BOOST_ROOT_DIR}
I've added a check. We'll hopefully support Windows soon but just haven't had time

2019-04-15 18:35 UTC, tmccrmck commented on cmake/get_boost.cmake
> +	set(CMAKE_FIND_LIBRARY_PREFIXES ${CMAKE_STATIC_LIBRARY_PREFIX})
Removed.

2019-04-15 18:36 UTC, tmccrmck commented on cmake/get_boost.cmake
> +	set(BOOST_INCLUDE_DIR ${install_dir}/include)
Removed.

2019-04-15 18:36 UTC, tmccrmck commented on cmake/get_boost.cmake
> +	libraries_to_fullpath(BOOST_LIBRARIES)
Removed.

2019-04-15 18:36 UTC, tmccrmck commented on cmake/get_boost.cmake
> +	set(Boost_LIBRARIES ${BOOST_LIBRARIES})
Done.

2019-04-15 18:36 UTC, tmccrmck commented on cmake/get_boost.cmake
> +	set(BOOST_LIBRARYDIR ${install_dir}/lib)
Removed.

2019-04-15 18:37 UTC, tmccrmck commented on cmake/get_boost.cmake
> +	message(FATAL_ERROR "No COMPONENTS specified for Boost")
Done.

2019-04-15 18:39 UTC, tmccrmck commented on cmake/get_boost.cmake
> +			BUILD_COMMAND ./b2 install ${BOOST_MAYBE_STATIC} --prefix=${BOOST_ROOT_DIR} variant=${VARIANT} toolset=gcc ${BOOST_COMPONENTS_FOR_BUILD}
Unfortunately, `CMAKE_C_COMPILER_ID` gives us the compiler vendor which isn't always the correct compiler name. I'm going to try to let b2 infer it for now.

2019-04-15 21:11 UTC, merged